### ISSUE TITLE
Usunięcie zmiennych z pliku pipeline'a

### ISSUE THREAD

**Issue by maksnowak** [maksnowak/FileSharingSystem#15]
Nikt nie musi znać IP naszego serwera 😁

- [x] Dodać sekrety na GitHubie/Azure DevOps
- [x] Przenieść zmienne tam
- [x] Usunąć zmienne z azure-pipelines.yml

**Comment by BrunoSienkiewicz** [comment]
I created docker hub repository to store images.
https://hub.docker.com/repositories/pisproject

**Comment by maksnowak** [comment]
@BrunoSienkiewicz I get an unknown error when trying to go to the repo:
![image](https://github.com/user-attachments/assets/48b96c29-c742-4d4e-b543-f5fb498714aa)

**Comment by BrunoSienkiewicz** [comment]
Check this link: https://hub.docker.com/r/pisproject/file-transfer
I pushed some images and they should be visible in tags tab.
