### ISSUE TITLE
Save files to MongoDB from file transfer

### ISSUE THREAD

**Issue by BrunoSienkiewicz** [maksnowak/FileSharingSystem#25]
Create endpoint that handles saving and retrieval of files to MongoDB.

**Comment by BrunoSienkiewicz** [comment]
@maksnowak @Depermitto @Duszke333 @msadlej 
Model of data saved to MongoDB should look something like that?
``` Go
type File struct {
--
ID primitive.ObjectID `bson:"_id"`
Name string
OwnerId string `bson:"user_id"`
Tags []string
Data []byte
}
```
Where `Data` are bytes encrypted by encryption service

**Comment by maksnowak** [comment]
> @maksnowak @Depermitto @Duszke333 @msadlej 
> 
> Model of data saved to MongoDB should look something like that?
> 
> ``` Go
> 
> type File struct {
> 
> --
> 
> ID primitive.ObjectID `bson:"_id"`
> 
> Name string
> 
> OwnerId string `bson:"user_id"`
> 
> Tags []string
> 
> Data []byte
> 
> }
> 
> ```
> 
> Where `Data` are bytes encrypted by encryption service

I think so, maybe add an additional field for people who have access to the file (besides the owner)

@Duszke333 @Depermitto @msadlej thoughts?

**Comment by msadlej** [comment]
> @maksnowak @Depermitto @Duszke333 @msadlej Model of data saved to MongoDB should look something like that?
> 
> ```go
> type File struct {
> --
> ID primitive.ObjectID `bson:"_id"`
> Name string
> OwnerId string `bson:"user_id"`
> Tags []string
> Data []byte
> }
> ```
> 
> Where `Data` are bytes encrypted by encryption service

Looks good to me, maybe we could improve consistency with the naming of ID/Id?

**Comment by BrunoSienkiewicz** [comment]
Updated file struct:

```Go
type File struct {
--
FileID primitive.ObjectID `json:"id" "bson:"_id"`
FileName string `json:"file_name" "bson:"fileName"`
UserID string `json:"user_id" bson:"userID"`
Tags []string `json:"tags" bson:"tags"`
Data []byte `json:"data" bson:"data"`
HasAccess []string `json:"has_access" "bson:"hasAccess"` // List of user IDs
}
```

In the encryption service i will add support for basic CRUD operations on these fields via REST endpoints.

**Comment by maksnowak** [comment]
LGTM
