### ISSUE TITLE
CORS issues in accounts microservice

### ISSUE THREAD

**Issue by Duszke333** [maksnowak/FileSharingSystem#44]
Frontend cannot make any calls to the microservice due to CORS error.

**Comment by maksnowak** [comment]
Use the issue template please, the problem is limited to Chromium-based browsers only, the template would include that information

**Comment by Duszke333** [comment]
> Use the issue template please, the problem is limited to Chromium-based browsers only, the template would include that information

Made no sense to me as the only browser known to not have the issue is Firefox, the others fail miserably.

**Comment by maksnowak** [comment]
> > Use the issue template please, the problem is limited to Chromium-based browsers only, the template would include that information
> 
> 
> 
> Made no sense to me as the only browser known to not have the issue is Firefox, the others fail miserably.

Because almost every browser uses Chromium under the hood nowadays.
Microsoft Edge, Opera, Brave... all of them are based on Chromium. The only popular exceptions are Firefox and Safari (which we cannot test)
